spring:
  application:
    name: unit-service
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    url: jdbc:mysql://114.113.151.147:8066/svdm?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: hg765JHG765jhgjgh876JHG76uyg56F76Ruygt97t6r566ef
logging:  # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://114.113.151.147:8761/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 30 #拉取服务注册信息时间
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 15 #续约更新频率
    lease-expiration-duration-in-seconds: 45  #过期剔除时间
