eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 30000  #清理无效节点的时间间隔